name: Run Bun Tests & Upload Dated Reports

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun runtime
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run tests & generate timestamped report
        run: bun run test:json

      - name:  Create reports directory (in case missing)
        run: mkdir -p reports

      - name:  Upload all test reports (JSON + XML)
        uses: actions/upload-artifact@v4
        with:
          name: bun-test-reports
          path: |
            *.json
            *.xml
            reports/**/*.json
            reports/**/*.xml
